#!/bin/bash

echo "🔧 回调URL问题快速修复脚本"
echo "=================================="
echo ""

echo "🚨 紧急问题发现："
echo "从您的日志可以看到回调URL配置错误："
echo ""
echo "❌ 错误格式："
echo "https://www.wenpai.xyz/callbackhttps://*.netlify.app/callbackhttp://localhost:5173/callback"
echo ""
echo "✅ 正确格式应该是："
echo "https://www.wenpai.xyz/callback"
echo "https://*.netlify.app/callback"
echo "http://localhost:5173/callback"
echo ""

echo "🔧 立即修复步骤："
echo ""

echo "1️⃣ 登录Authing控制台"
echo "   - 访问：https://console.authing.cn/"
echo "   - 登录您的账户"
echo ""

echo "2️⃣ 找到应用配置"
echo "   - 进入您的应用：文派"
echo "   - 点击'应用配置'"
echo ""

echo "3️⃣ 修复登录回调URL"
echo "   - 找到'登录回调 URL'字段"
echo "   - 完全删除当前内容"
echo "   - 逐个添加以下URL（每行一个）："
echo ""

echo "   第一个URL："
echo "   https://www.wenpai.xyz/callback"
echo ""
echo "   第二个URL："
echo "   https://*.netlify.app/callback"
echo ""
echo "   第三个URL："
echo "   http://localhost:5173/callback"
echo ""

echo "4️⃣ 保存配置"
echo "   - 点击'保存'按钮"
echo "   - 等待1-2分钟让配置生效"
echo ""

echo "5️⃣ 测试验证"
echo "   - 返回应用测试登录功能"
echo "   - 确认回调URL格式正确"
echo ""

echo "⚠️  重要提醒："
echo "- 每个URL必须单独一行"
echo "- 不能有空格或特殊字符"
echo "- 保存后需要等待生效"
echo ""

echo "🎯 预期结果："
echo "修复后，回调URL应该正确跳转到："
echo "http://localhost:5173/callback?code=xxx&state=xxx"
echo "而不是当前的错误格式"
echo ""

echo "📞 如果问题持续："
echo "- 检查Authing控制台配置"
echo "- 清除浏览器缓存"
echo "- 重新测试登录流程" 